set_property SRC_FILE_INFO {cfile:{C:/Users/Lin Hongyu/Desktop/fulL vivado/project_24_12_24_Single_Cycle/project_24_12_24_Single_Cycle.srcs/constrs_1/new/testtest.xdc} rfile:../../../project_24_12_24_Single_Cycle.srcs/constrs_1/new/testtest.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports clk_i]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T19 [get_ports rx_i]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports tx_o]
