# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_11_26 Register_Controler/Project_24_11_26 Register_Controler.srcs/sources_1/ip/u2r_cmd_fifo/u2r_cmd_fifo.xci
# IP: The module: 'u2r_cmd_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_11_26 Register_Controler/Project_24_11_26 Register_Controler.srcs/sources_1/ip/u2r_cmd_fifo/u2r_cmd_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'u2r_cmd_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_11_26 Register_Controler/Project_24_11_26 Register_Controler.srcs/sources_1/ip/u2r_cmd_fifo/u2r_cmd_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'u2r_cmd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_11_26 Register_Controler/Project_24_11_26 Register_Controler.srcs/sources_1/ip/u2r_cmd_fifo/u2r_cmd_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u2r_cmd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_11_26 Register_Controler/Project_24_11_26 Register_Controler.srcs/sources_1/ip/u2r_cmd_fifo/u2r_cmd_fifo.xci
# IP: The module: 'u2r_cmd_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_11_26 Register_Controler/Project_24_11_26 Register_Controler.srcs/sources_1/ip/u2r_cmd_fifo/u2r_cmd_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'u2r_cmd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_11_26 Register_Controler/Project_24_11_26 Register_Controler.srcs/sources_1/ip/u2r_cmd_fifo/u2r_cmd_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'u2r_cmd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_11_26 Register_Controler/Project_24_11_26 Register_Controler.srcs/sources_1/ip/u2r_cmd_fifo/u2r_cmd_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u2r_cmd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
