# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/testtest.xdc

# IP: ip/datadata/datadata.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datadata || ORIG_REF_NAME==datadata} -quiet] -quiet
