create_clock -period 20.000 -name clk_i -waveform {0.000 10.000} [get_ports clk_i]
set_property PACKAGE_PIN U18 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property PACKAGE_PIN V17 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rx_i]
set_property PACKAGE_PIN T19 [get_ports rx_i]
set_property PACKAGE_PIN J15 [get_ports tx_o]
set_property IOSTANDARD LVCMOS33 [get_ports tx_o]
