set_property PACKAGE_PIN U18 [get_ports clk_i]
set_property PACKAGE_PIN E17 [get_ports key_0_i]
set_property PACKAGE_PIN E18 [get_ports key_1_i]
set_property PACKAGE_PIN M15 [get_ports led_0_o]
set_property PACKAGE_PIN M14 [get_ports led_1_o]
set_property PACKAGE_PIN K16 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports key_0_i]
set_property IOSTANDARD LVCMOS33 [get_ports key_1_i]
set_property IOSTANDARD LVCMOS33 [get_ports led_0_o]
set_property IOSTANDARD LVCMOS33 [get_ports led_1_o]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
create_clock -period 20.000 -name clk_i -waveform {0.000 10.000} [get_ports clk_i]
