webtalk_init -webtalk_dir C:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_09_24 ≈‹¬Ìµ∆/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_led_chaser_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 12 15:51:21 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b9756465-31d0-4bb3-84cc-c675b75970a6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b1452797e36b48978fe70b56fd961b61" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 7840H w/ Radeon 780M Graphics      " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "280 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7632_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4242655260 -regid "" -xml C:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_09_24 ≈‹¬Ìµ∆/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_led_chaser_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_09_24 ≈‹¬Ìµ∆/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_led_chaser_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Lin Hongyu/Desktop/fulL vivado/Project_24_09_24 ≈‹¬Ìµ∆/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_led_chaser_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
