# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/register_test.xdc

# IP: ip/inst_rom_1/inst_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_rom || ORIG_REF_NAME==inst_rom} -quiet] -quiet
