set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN K16 [get_ports rst_n]
set_property PACKAGE_PIN T19 [get_ports rx]
set_property PACKAGE_PIN J15 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
