# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab10_1.xdc

# IP: ip/inst_rom/inst_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_rom || ORIG_REF_NAME==inst_rom} -quiet] -quiet
